### ISSUE TITLE
What is vpnbook IPSec?

### ISSUE THREAD

**Issue by yiakwy** [billniakas/vpnbook_refreshpass#1]
Besides passwd, we also need vpnbook shared secret for machine authentication. Could you tell me more about it?

**Comment by billniakas** [comment]
Can you please tell me exactly what do you mean? The only thing this script does is to see if the password in your text file is the same with the one in vpnbook webpage. In case you didn't know, you put the text file inside the folder with your .ovpn profiles and point the profiles to read the login credentials from it. 

If you have a suggestion, would you please elaborate?

**Comment by yiakwy** [comment]
Sorry you must be usng pptp CONNECTION. However, after boosted up to MacOS 10.12 Serria，we only have L2TP accepted. I have already found solutions by pinging algorithms to different VPN 
servers
